config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "search"=>"searches#search"

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
  end
# DM機能
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :notifications, only: [:destroy]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :subject, polymorphic: true
  belongs_to :user

  enum action_type: { commented_to_own_post: 0, favorited_to_own_post: 1, followed_me: 3}

end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
# 通知一覧
  def index
    @notifications = current_user.notifications.order(created_at: :desc)
    @notifications.where(checked: false).each do |notification|
      notification.update(checked: true)
    end
  end

# 通知の全削除
  def destroy
    @notifications = current_user.notifications.destroy_all
    redirect_to user_notifications_path(current_user)
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper

  def transition_path(notification)
    case notification.action_type.to_sym
    when :commented_to_own_post
      post_path(notification.subject.post, anchor: "comment-#{notification.subject.id}")
    when :liked_to_own_post
      post_path(notification.subject.post)
    when :followed_me
      post_path(notification.subject.follower)
    end
  end

end

app/views/notifications/_commented_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.name, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_path(notification.subject.post) %>
    にコメントしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/_favorited_to_own_post.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.user.name, user_path(notification.subject.user) %>
    があなたの
    <%= link_to '投稿', post_path(notification.subject.post) %>
    にいいねしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/_followed_me.html.erb
<%= link_to transition_path(notification) do %>
  <div>
    <%= link_to notification.subject.follower.name, user_path(notification.subject.follower) %>
    があなたをフォローしました
    <%= " (#{time_ago_in_words(notification.created_at)}前)" %>
  </div>
<% end %>

app/views/notifications/index.html.erb
<div class="container mb-5">

  <div class="row justify-content-center mt-5">
    <div class="col-md-8">
      <h4>通知一覧</h4>
    </div>
  </div>

  <% if @notifications.present? %>
    <div class="row justify-content-center">
      <div class="col-md-8 text-right">
        <%= link_to notification_path(@notifications), method: :delete, class: "btn btn-danger" do %>
          <i class="fa-solid fa-trash"></i>
        <% end %>
      </div>
    </div>

    <div class="row justify-content-center">
      <div class="col-md-8">
        <% @notifications.each do |notification| %>
          <div class="card my-2 px-3 py-3">
            <%= render "#{notification.action_type}", notification: notification %>
          </div>
        <% end %>
      </div>
    </div>
  <% else %>
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <p>通知はありません</p>
      </div>
    </div>
  <% end %>

</div>