config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "search"=>"searches#search"

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
  end
# DM機能
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :notifications, only: [:destroy]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
# DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
# 投稿閲覧数表示 
  has_many :view_counts, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

# フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
# フォロー一覧画面（あるユーザーにフォローされたユーザーを参照）
  has_many :followings, through: :relationships, source: :followed
# フォロワー一覧画面で使う（あるユーザーをフォローしたユーザーを参照）
  has_many :followers, through: :reverse_of_relationships, source: :follower

# フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
# フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
# フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

# プロフィール画像
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

# 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

# ゲストログイン
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
# ゲストユーザーかどうかを判定するメソッド
  def guest?
    email == 'guest@example.com'
  end


end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_sign_in
    user = User.guest
    sign_in user
    redirect_to user_path(user), notice: "ゲストユーザーとしてログインしました"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    # ページネーション、新規ユーザーが上に来るように
    @users = User.page(params[:page]).order(created_at: :desc)
  end

  def show
    @user = User.find(params[:id])
  # DM機能
    @currentUserEntry=Entry.where(user_id: current_user.id)
    @userEntry=Entry.where(user_id: @user.id)
    if @user.id == current_user.id
    else
      @currentUserEntry.each do |cu|
        @userEntry.each do |u|
          if cu.room_id == u.room_id then
            @isRoom = true
            @roomId = cu.room_id
          end
        end
      end
      if @isRoom
      else
        @room = Room.new
        @entry = Entry.new
      end
    end
  # ページネーション、新着投稿が上になるように
    @posts = @user.posts.page(params[:page]).order(created_at: :desc)
  end

  # お気に入り投稿一覧用
  def favorites
    @user = User.find(params[:id])
    favorites = Favorite.where(user_id: @user.id).pluck(:post_id)
    @favorite_posts = Post.where(id: favorites).page(params[:page])
  end


  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "ユーザー情報を更新しました"
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "ユーザー情報の更新ができませんでした"
      render :edit
    end
  end

  # ユーザー退会(削除)用
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:notice] = 'ユーザーを削除しました。'
    redirect_to :root #削除に成功すればrootページに戻る
  end



private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction, :email)
  end

# 権限設定
  def is_matching_login_user
    user = User.find(params[:id])
  # ログインユーザーが管理者ユーザーかどうかを確認、管理者ユーザーの場合は通貨させる
    if current_user.admin?
      return
    end
  # ログインユーザーと編集対象のユーザーが一致しない場合はリダイレクト
    unless user.id == current_user.id
      redirect_to user_path(current_user.id)
    end
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_index.html.erb
<div class="container mt-3 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% users.each do |user| %>
      <% unless user.guest? %> <!-- ゲストユーザーを除外 -->
      <div class="card mb-3">
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <p><%= image_tag user.get_profile_image, width: 100, height: 100 %></p>
            </div>
            <div class="col-md-9">
              <p><strong>ユーザーネーム：</strong><%= link_to user.name, user_path(user) %></p>
              <p><strong>自己紹介：</strong><%= user.introduction %></p>
              <span class="mr-3">フォロー: <%= user.followings.count %></span>
              <span class="mr-3">フォロワー: <%= user.followers.count %></span>
              <span class="float-right">
                <% if current_user %>
                  <% if current_user != user %>
                    <% if current_user.following?(user) %>
                      <%= link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-outline-secondary" %>
                    <% else %>
                      <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-outline-primary" %>
                    <% end %>
                  <% end %>
                <% end %>
              </span>
            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
<!--ページネーション-->
    <div class="pagination">
      <%= paginate users %>
    </div>
    
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container">
  <div class="row no-gutters my-4">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
<!--失敗フラッシュメッセージ-->
      <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <h5 class="text-light bg-dark py-4 mb-0">プロフィール編集</h5>
      <div class="form-body bg-light p-4">
        <div class="mx-auto text-center">
          <p>編集したい内容を入力してください</p>
        </div>
        <hr>
        <%= form_with model: @user do |f| %>
          <div class="input-group mb-3">
            <%= f.file_field :profile_image, accept: "image/*" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_field :name, class: "form-control", placeholder: "ユーザーネーム" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_area :introduction, class: "form-control", placeholder: "自己紹介（好きな生き物など）" %>
          </div>
<!--エラーメッセージ-->
          <% if @user.errors[:name].any? %>
            <div class="alert alert-danger">
              <%= @user.errors[:name].join(', ') %>
            </div>
          <% end %>
<!--更新、削除（退会）ボタン-->
          <%= f.submit "更新", class: "btn btn-lg btn-block btn-info mt-5" %>
          <%= link_to "削除",user_path(@user.id), class: "destroy-user btn btn-outline-danger btn-lg btn-block mt-3", method: :delete, "data-confirm" => "本当にこのユーザーを削除しますか？" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/favorites.html.erb
<!--いいねした投稿の一覧-->
<div class="container">
  <div class="row justify-content-center mt-5">
    <div class="col-md-8">
      <h4><%= @user.name %>のお気に入り投稿一覧</h4>
    </div>
  </div>
</div>
<!--投稿一覧の部分テンプレート呼び出し-->
<%= render 'posts/index', posts: @favorite_posts %>
<!-- お気に入り投稿が空の場合にメッセージを表示 -->
<% if @favorite_posts.empty? %>
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-8 text-center">
        <p>お気に入りの投稿はまだありません</p>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<!--検索フォーム-->
<%= render 'searches/search' %>
<!--ユーザー一覧-->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h4>ユーザー一覧</h4>
    </div>
  </div>
</div>
<!--ユーザー一覧の部分テンプレート呼び出し-->
<%= render 'index', users: @users %>

app/views/users/show.html.erb
<!--ユーザー詳細-->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8">
<!--成功フラッシュメッセージ-->
      <% if flash[:notice].present? %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div class="row bg-light">
        <div class="col-md-6">
          <h3 class="pt-3">プロフィール</h3>
        </div>
        <div class="col-md-6 text-right">

          <!--フォローボタン　ログインしてるユーザー本人以外の詳細ページのみに表示-->
          <div class="text-right pt-3">
            <% if user_signed_in? %>
              <% if current_user != @user %>
                <% if current_user.following?(@user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-outline-secondary" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-outline-primary" %>
                <% end %>
              <% end %>
            <% end %>
          </div>
        </div>
      </div>

      <div class="row bg-light p-3">
        <div class="col-md-4 mb-3">
          <%= image_tag @user.get_profile_image, width: 150, height: 150 %>
        </div>
        <div class="col-md-8">
          <h5>ユーザーネーム：<%= @user.name %></h5>
          <p>自己紹介：<%= @user.introduction %></p>
          <p>登録日：<%= @user.created_at.strftime('%Y/%m/%d') %></p>
          <p>投稿数：<%= @user.posts.count %></p>

          <span class="mr-4"><%=link_to"お気に入り投稿",favorites_user_path(@user) %></span>

          <span class="mr-2">
            <%= link_to user_followings_path(@user) do %>
              <%= @user.followings.count %>フォロー
            <% end %>
          </span>

          <span class="mr-2">
            <%= link_to user_followers_path(@user) do %>
              <%= @user.followers.count %>フォロワー
            <% end %>
          </span>

        <!--DM機能、チャットボタン-->
          <div class="text-right">
            <% unless @user.id == current_user.id %>
              <% if (current_user.following? @user) && (@user.following? current_user)  %>
              <% if @isRoom == true %>
                <p class="user-show-room"><a href="/rooms/<%= @roomId %>" class="btn btn-outline-primary">チャットへ</a>
              <% else %>
                <%= form_for @room do |f| %>
                  <%= fields_for @entry do |e| %>
                    <%= e.hidden_field :user_id, value: @user.id %>
                  <% end %>
                  <%= f.submit "チャット", class:"btn btn-outline-primary user-show-chat"%>
                <% end %>
              <% end %>
              <% end %>
            <% end %>
          </div>

          <!--ユーザーの編集ボタン　ログインしてるユーザー本人と管理者ユーザーにのみに表示-->
          <div class="text-right">
            <% if user_signed_in? && @user == current_user || user_signed_in? && current_user.admin? %>
              <% unless @user.email == "guest@example.com" then %>
              <% unless @user.email == "admin@example.jp" then %>
                <%= link_to edit_user_path(@user.id), class: "btn btn-outline-success" do %>
                  <i class="fa-solid fa-user-gear"></i>
                <% end %>
              <% end %>
              <% end %>
            <% end %>
          </div>

        </div>
      </div>

    </div>
  </div>
</div>

<!--投稿一覧-->
<div class="container mt-4">
  <div class="row justify-content-center">
    <div class="col-md-8 text-center">
      <hr>
      <h3>投稿</h3>
    </div>
  </div>
  <% if @posts.any? %> <!-- @postsに投稿があるかどうかをチェック -->
    <%= render 'posts/index', posts: @posts %>
  <% else %>
    <div class="row justify-content-center">
      <div class="col-md-8　text-center">
        <p>まだ投稿がありません。</p>
      </div>
    </div>
  <% end %>
</div>