config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "search"=>"searches#search"

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
  end
# DM機能
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :notifications, only: [:destroy]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy
# 投稿閲覧数表示
  has_many :view_counts, dependent: :destroy

  validates :title, presence: { message: "タイトルは必須です" }
  validates :body, presence: { message: "本文は必須です" }

  def get_image
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id) if user
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :is_matching_login_user, only: [:edit, :update, :destroy]

  def index
    # ページネーション、新着の投稿が上になるように
    @posts = Post.page(params[:page]).order(created_at: :desc)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    if @post.save
      flash[:notice] = "投稿に成功しました"
      redirect_to post_path(@post)
    else
      flash.now[:alert] = "投稿に失敗しました"
      render :new
    end
  end

  def show
    @post = Post.find(params[:id])
    unless ViewCount.where(created_at: Time.zone.now.all_day).find_by(user_id: current_user.id, post_id: @post.id)
      current_user.view_counts.create(post_id: @post.id)
    end
    @user = @post.user
    @post_comment = PostComment.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      flash[:notice] = "投稿を更新しました"
      redirect_to post_path(@post.id)
    else
      flash.now[:alert] = "投稿の更新ができませんでした"
      render :edit
    end
  end

  def destroy
    post = Post.find(params[:id])
    post.destroy
    redirect_to posts_path
  end


  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

# 権限設定
  def is_matching_login_user
    post = Post.find(params[:id])
# ログインユーザーが管理者ユーザーかどうかを確認、管理者ユーザーの場合は通貨させる
    if current_user.admin?
      return
    end
# ログインユーザーと編集対象のユーザーが一致しない場合はリダイレクト
    unless post.user.id == current_user.id
      redirect_to posts_path
    end
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_index.html.erb
<div class="container mt-3 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <% posts.each do |post| %>
      <% if post.user %>
      <div class="card mb-3">
        <p class="text-right my-2 mr-2">投稿日：<%= post.created_at.strftime('%Y/%m/%d') %></p>
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <p><%= image_tag post.user.get_profile_image, width: 70, height: 70 %></p>
              <p><%= link_to post.user.name, user_path(post.user) %></p>
            </div>
            <div class="col-md-9">
              <h5 class="card-title">
                <%= link_to post.title, post_path(post) %>
                <% if post.get_image.attached? %>
                  <span class="badge ml-2">（投稿画像あり）</span>
                <% end %>
              </h5>
              <p class="card-text"><%= post.body %></p>

<!--コメント数-->
              <span class="mr-4"><i class="fa-regular fa-comment"></i><%= post.post_comments.count %></span>

<!--いいねボタン-->
              <span id="favorite_btn_<%= post.id %>">
                <%= render "favorites/favorite_btn", post: post %>
              </span>

<!--投稿閲覧数-->
              <span class="ml-4"><%= post.view_counts.count %></span>

            </div>
          </div>
        </div>
      </div>
      <% end %>
      <% end %>
<!--ページネーション-->
    <div class="pagination">
      <%= paginate posts %>
    </div>

    </div>
  </div>
</div>

app/views/posts/edit.html.erb
<div class="container">
  <div class="row no-gutters my-4">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
<!--失敗フラッシュメッセージ-->
      <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <h5 class="text-light bg-dark py-4 mb-0">投稿編集</h5>
      <div class="form-body bg-light p-4">
        <div class="mx-auto text-center">
          <p>編集したい内容を入力してください</p>
        </div>
        <hr>
        <%= form_with model: @post do |f| %>
          <div class="input-group mb-3">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_area :body, class: "form-control", placeholder: "本文" %>
          </div>
<!--エラーメッセージ-->
          <% if @post.errors[:title].any? %>
            <div class="alert alert-danger">
              <%= @post.errors[:title].join(', ') %>
            </div>
          <% end %>

          <% if @post.errors[:body].any? %>
            <div class="alert alert-danger">
              <%= @post.errors[:body].join(', ') %>
            </div>
          <% end %>
<!--更新ボタン、削除ボタン-->
          <%= f.submit "更新", class: "btn btn-lg btn-block btn-info mt-5" %>
          <%= link_to "削除", post_path(@post), method: :delete, class: "btn btn-outline-danger btn-lg btn-block mt-3", data: { confirm: "この投稿を本当に削除しますか?" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<!--検索フォーム-->
<%= render 'searches/search' %>
<!--投稿一覧-->
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
      <h4>投稿一覧</h4>
    </div>
  </div>
</div>
<!--投稿一覧の部分テンプレート呼び出し-->
<%= render 'posts/index', posts: @posts %>

app/views/posts/new.html.erb
<div class="container">
  <div class="row no-gutters my-4">
    <div class="col-md-5 col-sm-10 mx-2 mx-sm-auto text-center shadow-lg rounded px-0 my-5">
<!--失敗フラッシュメッセージ-->
      <% if flash[:alert].present? %>
        <div class="alert alert-danger">
          <%= flash[:alert] %>
        </div>
      <% end %>

      <h5 class="text-light bg-dark py-4 mb-0">新規投稿</h5>
      <div class="form-body bg-light p-4">
        <div class="mx-auto text-center">
          <p>投稿したい内容を入力してください</p>
        </div>
        <hr>
        <%= form_with model: @post do |f| %>
          <div class="input-group mb-3">
            <%= f.file_field :image, accept: "image/*" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_field :title, class: "form-control", placeholder: "タイトル" %>
          </div>
          <div class="input-group mb-3">
            <%= f.text_area :body, class: "form-control", placeholder: "本文" %>
          </div>
<!--エラーメッセージ-->
          <% if @post.errors[:title].any? %>
            <div class="alert alert-danger">
              <%= @post.errors[:title].join(', ') %>
            </div>
          <% end %>

          <% if @post.errors[:body].any? %>
            <div class="alert alert-danger">
              <%= @post.errors[:body].join(', ') %>
            </div>
          <% end %>

          <%= f.submit "投稿", class: "btn btn-lg btn-block btn-info mt-5" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="container mt-4 mb-5">
  <div class="row justify-content-center">
    <div class="col-md-8">
<!--成功フラッシュメッセージ-->
      <% if flash[:notice].present? %>
        <div class="alert alert-info">
          <%= flash[:notice] %>
        </div>
      <% end %>

      <div class="card">
        <p class="text-right my-2 mr-2">投稿日：<%= @post.created_at.strftime('%Y/%m/%d') %></p>
        <% if @post.get_image.attached? %>
          <%= image_tag @post.get_image, class: "card-img-top" %>
        <% end %>
        <div class="card-body">
          <div class="row">
            <div class="col-md-3">
              <p><%= image_tag @post.user.get_profile_image, width: 80, height: 80 %></p>
              <p><%= link_to @post.user.name, user_path(@post.user) %></p>
            </div>
            <div class="col-md-9">
              <h5 class="card-title"><%= @post.title %></h5>
              <p class="card-text"><%= @post.body %></p>
<!--コメント数-->
              <span id="comment_counter">
                <%= render 'post_comments/counter', post: @post %>
              </span>
<!--いいねボタン-->
              <span id="favorite_btn_<%= @post.id %>">
                <%= render "favorites/favorite_btn", post: @post %>
              </span>
<!--投稿閲覧数-->
              <span class="ml-4"><%= @post.view_counts.count %></span>
<!--投稿の編集ボタン（削除ボタンは編集ページに配置）-->
              <p class="text-right my-2 mr-2">
                <% if @post.user == current_user || user_signed_in? && current_user.admin? %>
                  <%= link_to edit_post_path(@post), class: "btn btn-outline-success" do %>
                    <i class="fa-solid fa-pen"></i>
                  <% end %>
                <% end %>
              </p>

            </div>
          </div>

<!--コメントセクション-->
          <hr>
  <!--コメント一覧-->
          <label>コメント</label>
          <div id="comment_index" class="comment-container">
            <%= render 'post_comments/index', post: @post %>
          </div>
  <!--コメントフォーム-->
          <%= render 'post_comments/form', post: @post, post_comment: @post_comment %>
<!--コメントセクション-->

        </div>
      </div>

    </div>
  </div>
</div>