config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "homes#top"
  get "search"=>"searches#search"

  resources :posts, only: [:new, :create, :index, :show, :edit, :update, :destroy] do
    resource :favorites, only: [:create, :destroy]
    resources :post_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update, :destroy] do
    member do
      get :favorites
    end
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    resources :notifications, only: [:index]
  end
# DM機能
  resources :messages, only: [:create]
  resources :rooms, only: [:create,:show]

  resources :notifications, only: [:destroy]

  devise_scope :user do
    post "users/guest_sign_in", to: "users/sessions#guest_sign_in"
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :post

# 通知機能用
  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    # 自分の投稿にいいねした場合は通知を作成しない
    return if self.user == self.post.user
    Notification.create(subject: self, user: self.post.user, action_type: :favorited_to_own_post)
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :room
  # 空でない、最大140字まで
  validates :message, presence: true, length: { maximum: 140 }
end

app/models/notification.rb
class Notification < ApplicationRecord

  belongs_to :subject, polymorphic: true
  belongs_to :user

  enum action_type: { commented_to_own_post: 0, favorited_to_own_post: 1, followed_me: 3}

end

app/models/post.rb
class Post < ApplicationRecord

  belongs_to :user
  has_one_attached :image
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_one :notification, as: :subject, dependent: :destroy
# 投稿閲覧数表示
  has_many :view_counts, dependent: :destroy

  validates :title, presence: { message: "タイトルは必須です" }
  validates :body, presence: { message: "本文は必須です" }

  def get_image
    image
  end

  def favorited_by?(user)
    favorites.exists?(user_id: user.id) if user
  end

  def self.looks(search, word)
    if search == "perfect_match"
      @post = Post.where("title LIKE?", "#{word}")
    elsif search == "partial_match"
      @post = Post.where("title LIKE?", "%#{word}%")
    else
      @post = Post.all
    end
  end

end

app/models/post_comment.rb
class PostComment < ApplicationRecord

  belongs_to :user
  belongs_to :post
  validates :comment, presence: true

# 通知機能用
  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private

  def create_notifications
    # 自分の投稿にコメントした場合は通知を作成しない
    return if self.user == self.post.user
    Notification.create(subject: self, user: post.user, action_type: :commented_to_own_post)
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord

# フォローしたユーザー
  belongs_to :follower, class_name: "User"
# フォローされたユーザー
  belongs_to :followed, class_name: "User"
  # class_name: "User"でuserテーブルからデータを取得

# 通知機能用
  has_one :notification, as: :subject, dependent: :destroy

  after_create_commit :create_notifications

  private
  def create_notifications
    Notification.create(subject: self, user: followed, action_type: :followed_me)
  end

end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one_attached :profile_image
  has_many :posts, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :notifications, dependent: :destroy
# DM機能
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
# 投稿閲覧数表示 
  has_many :view_counts, dependent: :destroy

  validates :name, presence: true
  validates :email, presence: true
  validates :encrypted_password, presence: true

# フォローをした、されたの関係
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
# フォロー一覧画面（あるユーザーにフォローされたユーザーを参照）
  has_many :followings, through: :relationships, source: :followed
# フォロワー一覧画面で使う（あるユーザーをフォローしたユーザーを参照）
  has_many :followers, through: :reverse_of_relationships, source: :follower

# フォローしたときの処理
  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
# フォローを外すときの処理
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
# フォローしているか判定
  def following?(user)
    followings.include?(user)
  end

# プロフィール画像
  def get_profile_image
    unless profile_image.attached?
      file_path = Rails.root.join('app/assets/images/no_image.jpg')
      profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
    end
    profile_image
  end

# 検索機能
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?", "%#{word}%")
    else
      @user = User.all
    end
  end

# ゲストログイン
  GUEST_USER_EMAIL = "guest@example.com"

  def self.guest
    find_or_create_by!(email: GUEST_USER_EMAIL) do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = "ゲスト"
    end
  end
# ゲストユーザーかどうかを判定するメソッド
  def guest?
    email == 'guest@example.com'
  end


end

app/models/view_count.rb
class ViewCount < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<!--ヘッダー-->
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container">
    <a class="navbar-brand p-3" href="/"><strong>いきものとくらす</strong></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">

<!--ナビゲーションメニュー-->
      <ul class="navbar-nav ml-auto">
<!--ログインしていたら-->
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to user_notifications_path(current_user), class: 'nav-link text-dark' do %>
            <% if current_user.notifications.where(checked: false).exists? %>
              <i class="fa-sharp fa-solid fa-bell" style="color: red;"></i>
            <% else %>
              <i class="fa-sharp fa-solid fa-bell"></i>
            <% end %>
            通知
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link text-dark' do %>
            <i class="fa-solid fa-image"></i> 投稿
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link text-dark' do %>
            <i class="fas fa-users"></i> ユーザー
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_post_path, class: 'nav-link text-dark' do %>
            <i class="fa-solid fa-pen-to-square"></i> 新規投稿
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to user_path(current_user.id), class: 'nav-link text-dark' do %>
            <i class="fa-solid fa-circle-user"></i> マイページ
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to destroy_user_session_path, method: :delete, class: 'nav-link text-dark' do %>
            <i class="fas fa-sign-out-alt"></i> ログアウト
          <% end %>
        </li>
<!--ログインしていなかったら-->
      <% else %>
        <li class="nav-item">
          <%= link_to posts_path, class: 'nav-link text-dark' do %>
            <i class="fa-solid fa-image"></i> 投稿
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to users_path, class: 'nav-link text-dark' do %>
            <i class="fas fa-users"></i> ユーザー
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_registration_path, class: 'nav-link text-dark' do %>
            <i class="fas fa-user-plus"></i> 登録
          <% end %>
        </li>
        <li class="nav-item">
          <%= link_to new_user_session_path, class: 'nav-link text-dark' do %>
            <i class="fas fa-sign-in-alt"></i> ログイン
          <% end %>
        </li>
      <% end %>
      </ul>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IkimonoToKurasu</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <script src="https://kit.fontawesome.com/6106f3c26d.js" crossorigin="anonymous"></script>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<!--ヘッダー-->
    <header>
      <%= render 'layouts/header' %>
    </header>

<!--各コンテンツ-->
    <main class="contents">
      <%= yield %>
    </main>

<!--フッター-->
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-3">
            <p>生き物好きが集まるSNS</p>
            <p><strong>いきものとくらす</strong></p>
          </div>
          <div class="col-md-9 text-right">
            <span><img src="<%= asset_path('クロネコアイコン2.png') %>" alt="ロゴ" style="width: 80px; max-height: auto; object-fit: contain;"></span>
          </div>
        </div>
      </div>
    </footer>

  </body>
</html>